### ISSUE TITLE
Spike: Compile assets/docs needed for Android and iPhone

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#10]
- Terms and conditions
- Screenshots
- Business use case??
- Generate [video](https://docs.google.com/document/d/1-ZdqK17DLAF5VS_tPEf9buvlLQSzdYeoJjl4gSRShEo/edit#heading=h.n1rogg5utrj2) of entire flow with @Louisreed

**Comment by vpetersson** [comment]
> Terms and conditions

Yeah I don't think we have that ready atm. Just put in a place holder for the time being.

> Screenshots

We should be able to pull that fairly easily from either the emulator of screenshots on the device directly once it works end-to-end

> Business use case??

To be HIP19 compliant :)

> Generate video

Good idea!

**Comment by marvinmarnold** [comment]
On the Apple side, the account holder, @shawaj needs to login and accept some agreement. 

![Screen Shot 2022-02-26 at 3 57 01 PM](https://user-images.githubusercontent.com/1311030/155860395-be6a58d2-cdc4-4683-8914-2e3424476fe8.png)

**Comment by marvinmarnold** [comment]
And I don't have access to the Android Play store account FYI

**Comment by shawaj** [comment]
@marvinmarnold Apple thing sorted.

Re Google your Nebra email account has access 👍

**Comment by marvinmarnold** [comment]
> Re Google your Nebra email account has access

Thanks. Never found an invitation but was able to login directly from the Play console.

**Comment by shawaj** [comment]
Strange but glad you could get in 🙌

**Comment by marvinmarnold** [comment]
This is now being tracked in: https://github.com/NebraLtd/maker-starter-app/issues/11
