### ISSUE TITLE
Update user interface to be more user friendly

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/maker-starter-app#103]
Based on conversation: https://nebraltd.slack.com/archives/C0XGF69SN/p1649194385699389?thread_ts=1649190445.851989&cid=C0XGF69SN

**Acceptance criteria:**
First page(Pre login to Helium):
- Convert the 2 sentences to buttons so that the user understand it's clickable
- Update "Nebra Helium" to "Nebra Hotspot"

**Comment by Andrewsopoku** [comment]
@posterzh these issues already have tickets

**Comment by posterzh** [comment]
@Andrewsopoku Could you strike out the issues already exist?

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/110
