### ISSUE TITLE
Password text color is faded out in WiFi connection screen

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/maker-starter-app#111]
The foreground color of the password text is faded out.
![image](https://user-images.githubusercontent.com/91350131/163273522-4f334fcf-04ac-4f75-bde3-3f83de8ec589.png)

**Acceptance criteria:**
- As a user, I can recognize the password length and transient appearance of characters.

**Comment by marvinmarnold** [comment]
@posterzh can you move this issue to the correct column on Zenhub?

**Comment by posterzh** [comment]
@marvinmarnold Sure

**Comment by marvinmarnold** [comment]
@posterzh the related PR is merged. Shouldn't this be closed?

**Comment by posterzh** [comment]
Yes, this can be merged. It's tested after merging.
