### ISSUE TITLE
Hotspot options/details text invisible

### ISSUE THREAD

**Issue by Louisreed** [NebraLtd/maker-starter-app#112]
In dark mode on Android the text is invisible, white text is clashing with the light background

![image](https://user-images.githubusercontent.com/9106988/163396511-a57e6927-3fa9-4c23-ab8c-aaf83f344bba.png)

**Comment by Andrewsopoku** [comment]
@Louisreed I don't seem to replicate the issue.
Are you using the latest version of the app?
Also can you give some info on your mobile device

**Comment by Andrewsopoku** [comment]
@Louisreed Please any update with this?

**Comment by Louisreed** [comment]
@Andrewsopoku I reinstalled the app and the issue seems to be resolved now!
