### ISSUE TITLE
Update iOS and Android store images for final publish

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#116]
**Acceptance Criteria**
- Android: Phone uploaded to Google Play
- Android: 7inch tablet uploaded to Google Play
- Android: 10inch tablet uploaded to Google Play
- Instructions for mocking a wallet when using the emulator in README

**Comment by Andrewsopoku** [comment]
**iPhone 13**
![Simulator Screen Shot - iPhone 13 - 2022-04-26 at 15 29 29](https://user-images.githubusercontent.com/20680743/165513293-bb8f4019-2072-4635-95e0-2eac0ee200d7.png)


![Simulator Screen Shot - iPhone 13 - 2022-04-26 at 15 28 44](https://user-images.githubusercontent.com/20680743/165513309-7fa4fc9c-b517-4685-adf8-f4fdadf4a96c.png)

**Comment by Louisreed** [comment]
@marvinmarnold @Andrewsopoku
![2022-04-28 10 53 22](https://user-images.githubusercontent.com/9106988/165727311-b05b6ce4-2023-4ad2-aebb-522afad2d717.jpg)
![2022-04-28 10 53 20](https://user-images.githubusercontent.com/9106988/165727316-fbc4d5df-11b5-474a-8dce-b8d01c159a01.jpg)
![2022-04-28 10 53 18](https://user-images.githubusercontent.com/9106988/165727318-3e4c3912-f839-4eda-aeb0-44a321e61a66.jpg)
![2022-04-28 10 53 15](https://user-images.githubusercontent.com/9106988/165727321-64c9137d-0e92-414e-9868-cc051f85b09c.jpg)
![2022-04-28 10 53 12](https://user-images.githubusercontent.com/9106988/165727322-9255f81d-0f41-4533-9e4e-52aedd8ca823.jpg)
![2022-04-28 10 50 40](https://user-images.githubusercontent.com/9106988/165727323-69d67a44-2147-49a7-a396-99c0556e33e6.jpg)
![2022-04-28 10 50 34](https://user-images.githubusercontent.com/9106988/165727324-73cc1b22-bd0c-463b-b9e2-590973a0180b.jpg)
![2022-04-28 10 50 37](https://user-images.githubusercontent.com/9106988/165727326-d4682346-9ff5-4fed-9352-f34fcab99a56.jpg)

**Comment by Andrewsopoku** [comment]
**IPHONE 8**
![Simulator Screen Shot - iPhone 8 Plus - 2022-05-11 at 18 59 00](https://user-images.githubusercontent.com/20680743/167916218-3ed70987-feb4-4a4c-bb23-290427c04eea.png)

![Simulator Screen Shot - iPhone 8 Plus - 2022-05-11 at 19 01 45](https://user-images.githubusercontent.com/20680743/167916241-065b3efc-23b4-40da-b4c7-2665b5292da6.png)
