### ISSUE TITLE
Unable to update antenna only

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#117]
Moved from: https://github.com/NebraLtd/hm-dashboard/issues/957

After trying to update antenna only, screen loads forever and never hands over to Helium App. Have tried both custom antenna type and Nebra stock antenna type.

![signal-2022-04-15-113414_001.png](https://images.zenhubusercontent.com/6111782bbed147dc514083ae/6ecc1ddd-3197-4bb2-8055-a6442652dd2a)

**Acceptance Criteria**
- There should be "Update Antenna" on hotspot item action menu
- On clicking "Update Antenna", user should be able to update antenna without asserting location

**Comment by marvinmarnold** [comment]
@Andrewsopoku @posterzh

**Comment by marvinmarnold** [comment]
I don't see a way to get around adding another button for update antenna only. Currently, the location assertion always jumps to the location of the user, not the current location of the hotspot. That makes it impossible (very very difficult) for the user to keep the same location as before because they need to manually scroll to the exact same GPS coordinates. 

We could change this default behavior, but it will be easier and better UX if we create another button so the user can choose to edit the antenna only.

**Comment by Andrewsopoku** [comment]
@marvinmarnold i am unable to replicate the issue, as every time i try i am sent to Helium app complete the transaction. However, with the current design of the Nebra app, it's just not possible to update the antenna only as you mentioned. 

An easier approach is to set the GPS location to the current Hotspot coordinates but with that, we will have to test if indeed the user will not be charged if the location hash doesn't change

A stretched approach will be having "Hotspot Update" and "Antenna update" separated.

**Comment by marvinmarnold** [comment]
@posterzh are you able to replicate this?

**Comment by posterzh** [comment]
@marvinmarnold I was able to reproduce this error a few days ago, but I can't now.

**Comment by posterzh** [comment]
After updating antenna, the page was hang out since the onboarding record couldn't be fetched. It maybe the server problem but the maker app should handle this case gracefully.
