### ISSUE TITLE
Unable to search address during location assertion

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#118]
Consider removing feature if it will be too complex to get working quickly

**Comment by marvinmarnold** [comment]
@Andrewsopoku @posterzh

**Comment by Andrewsopoku** [comment]
@marvinmarnold below is the error message causing the issue.

{"error_message": "This API project is not authorized to use this API.", "predictions": [], "status": "REQUEST_DENIED"}

It is most likely Google place hasn't been activated for the api key we are using. I checked google console but i dont have access to the App project there. Please are you able to check from Google Console if Google place is active for the project?

**Comment by marvinmarnold** [comment]
@Andrewsopoku Maps JavaScript API and Places API are now enabled. Can you check if it's working now?
