### ISSUE TITLE
Location assertion always says fee will be paid by Nebra

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#119]
This is displayed even if the hotspot has already used its free quota.

![image](https://user-images.githubusercontent.com/1311030/163603016-1d65a673-9cb8-44e9-8162-d45e3a477328.png)

Please confirm we are not paying for these subsequent location assertions

** Acceptance Criteria **
- For onboarding, the Location Update Confirmation page should show the current message (Your location fee($10) has been prepaid)
- For subsequent location/antenna update,  the Location Update Confirmation page should show the message ("You need to a $10 Location fee (in DC) to confirm this location.")

**Comment by marvinmarnold** [comment]
@Andrewsopoku @posterzh

**Comment by Andrewsopoku** [comment]
I can confirm that the maker doesn't payer for subsequent hotspot updates. The labels are wrong. The below transaction was made from Nebra app.
![IMG_0822](https://user-images.githubusercontent.com/20680743/163790378-e51dddba-ea4a-4df1-8ad0-2709c6e7683d.jpg)

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/124
