### ISSUE TITLE
Use correct secrets and endpoints

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#12]
- Onboarding server (hardcoded in [App.tsx](https://github.com/NebraLtd/maker-starter-app/blob/6813eb34642b6c3bf5fa2bf1aeb61b54d0606cfb/src/App.tsx#L125))
- https://github.com/NebraLtd/maker-starter-app/blob/2a1082bb7dbfa359feb64daa0c570c9f6fba0aee/README.md?plain=1#L60

**Comment by marvinmarnold** [comment]
@vpetersson have you already created keys for Google Maps or Mapbox?

**Comment by marvinmarnold** [comment]
@vpetersson btw you will need to create a new Mapbox style and copy the link. Just saw this, but yea I can create the Google Maps one.

![Screen Shot 2022-03-08 at 4 30 36 PM](https://user-images.githubusercontent.com/1311030/157336991-adc0995f-2c68-4fe4-8cd8-31fe480222b8.png)
![Screen Shot 2022-03-08 at 4 31 01 PM](https://user-images.githubusercontent.com/1311030/157336998-6db0f308-149f-4915-918e-d0ea17afb283.png)

**Comment by marvinmarnold** [comment]
@Andrewsopoku @posterzh I created `Nebra App (maker-starter-app) .env` in 1Password for these values. It is still using a temporary `MAPBOX_STYLE_URL`. You can use this for building test releases.

**Comment by Andrewsopoku** [comment]
Well noted

**Comment by vpetersson** [comment]
@marvinmarnold i've added the updated ones to 1password.

**Comment by posterzh** [comment]
Cool

**Comment by marvinmarnold** [comment]
@posterzh @Andrewsopoku can you test the `.env` found on 1Password under `Nebra App (maker-starter-app) .env`? It should now contain the working values at top.

**Comment by posterzh** [comment]
@marvinmarnold It works well.
