### ISSUE TITLE
Should not crash when asserting a location for a gateway that does not belong to Nebra

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#120]
![signal-2022-04-15-113414_001](https://user-images.githubusercontent.com/1311030/163603422-dbbc16eb-5079-4d02-9758-8dc2b9ed6a90.png)

**Acceptance criteria**
- If hotspot does not exist in onboarding server, user should always have to pay fee and app should not hang

**Comment by Andrewsopoku** [comment]
@marvinmarnold Should you be able to assert location for such hotspots?

**Comment by marvinmarnold** [comment]
@Andrewsopoku "should" can mean a lot of things. In one sense, we aren't supporting other manufacturers, so we don't need to support this feature. That said, we are displaying hotspots from other manufacturers and this breaks the app. Given we have partially added support for other manufacturers, we either need to hide them completely, or add support, but we can't have broken features. I think it will be easier to support location assertion for them than remove them completely.

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/128
