### ISSUE TITLE
Link to/promote Dashboard

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#125]
**Acceptance criteria**
- On homepage
- "For additional insights, check out the Nebra Dashboard"
- Add UTM params for tracking

**Comment by marvinmarnold** [comment]
@Louisreed could use wireframes for this

**Comment by Andrewsopoku** [comment]
@Louisreed please any update on the wireframe?

**Comment by Louisreed** [comment]
@Andrewsopoku I'll get this over to you today

**Comment by marvinmarnold** [comment]
https://segment.com/docs/guides/how-to-guides/cross-channel-tracking/ fyi

**Comment by Louisreed** [comment]
@Andrewsopoku @marvinmarnold Thoughts? https://www.figma.com/file/6l7k7BRmW98AMmRxV01iVT/App?node-id=124%3A18
![Home Page - Notification - Dashboard](https://user-images.githubusercontent.com/9106988/166484371-adbde9b4-1522-4bef-a8f3-edc2469c3ae1.png)

**Comment by marvinmarnold** [comment]
@Louisreed it looks good but some thoughts:

- Do we want it to be a permanent message instead of closeable? Or @Andrewsopoku maybe it stays a popup but opens every team user enters the home screen?
- I'd change the trial to "Free Trial" instead of "New Update"

**Comment by Louisreed** [comment]
@marvinmarnold Yeah good point, I was thinking the pop up appears every time the app is reopened. This can be applied for a limited time and we can find a better permanent place to put it in the settings or other sub-menu etc.

**Comment by Andrewsopoku** [comment]
@Louisreed i think it will be annoying to the user if they have to close it for a number of times. How about making it permanent on the home screen?

**Comment by Louisreed** [comment]
@Andrewsopoku @marvinmarnold What about this version instead? 3 Styles to choose from:
![Home Page - Notification - Dashboard - Permanent-1](https://user-images.githubusercontent.com/9106988/166891598-76e1266e-2330-4611-850b-84d8fc9e9e2d.png)
![Home Page - Notification - Dashboard - Permanent-2](https://user-images.githubusercontent.com/9106988/166891621-5a31fbcf-8a4e-4a08-b19c-1d0df86dde4f.png)
![Home Page - Notification - Dashboard - Permanent -3](https://user-images.githubusercontent.com/9106988/166891623-976a73b0-b7d1-475d-b7e4-3c37bf70dcb6.png)

**Comment by Andrewsopoku** [comment]
@Louisreed Perfect. Can you add dark mode versions too

**Comment by Louisreed** [comment]
@Andrewsopoku Which style are we going with?

**Comment by Andrewsopoku** [comment]
<img width="918" alt="utm" src="https://user-images.githubusercontent.com/20680743/167615533-e85ec386-7c23-4d88-91e4-c3a6955faeae.png">
@marvinmarnold Please can i get some suggestion on the UTM values to use

**Comment by marvinmarnold** [comment]
- utm_id: nebra_app.1
- utm_source: nebra_app_ios or nebra_app_android
- utm_medium: app_home
- utm_campaign: nebra_app

Skip the rest. @Andrewsopoku

**Comment by Andrewsopoku** [comment]
utm_campaign: nebra_app -> Should it not be a name related to the dashboard rather?.
