### ISSUE TITLE
Establish manual build process for iPhone

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#13]
**Acceptance criteria**
For each of the three stages build, sign, and publish, include documentation for:

- List of necessary assets that need to be supplied: images, text files, etc
- Provide code snippets or link to detailed instructions
- Decisions taken: eg key params, build tool, etc

**Comment by Andrewsopoku** [comment]
Closed by https://github.com/NebraLtd/maker-starter-app/pull/23
