### ISSUE TITLE
Add Support as an extra tab

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/maker-starter-app#139]
We should add an extra tab for support. This should load the Freshdesk Portal Knowledge Base, possibly as a web page integration. It should default to articles surrounding help with the app and reaching out to the support. Other categories like troubleshooting the miners should be accessible through the menu

Related to: https://github.com/NebraLtd/maker-starter-app/issues/152

**Acceptance criteria**
- Icon added to toolbar
- Default to articles about the app
- Track tab switches with Segment

**Comment by Andrewsopoku** [comment]
@KevinWassermann94 Please can you share the url to embed?

**Comment by KevinWassermann94** [comment]
@Andrewsopoku https://support.nebra.com/support/home

**Comment by marvinmarnold** [comment]
@Louisreed can you make some simple wireframe for this?

**Comment by Louisreed** [comment]
@marvinmarnold Sure thing

**Comment by Louisreed** [comment]
@marvinmarnold @Andrewsopoku @KevinWassermann94 Thoughts?
![Home Page - Taskbar - Support Icon](https://user-images.githubusercontent.com/9106988/166950530-80a7fbad-46ec-4ea0-81de-9f102d886497.png)

![Home Page - Taskbar - Support Icon - Active](https://user-images.githubusercontent.com/9106988/166950524-09710eb1-d1eb-4fda-a8a8-9307ae7e5dc7.png)

**Comment by marvinmarnold** [comment]
Thanks!

@KevinWassermann94 do you know how to make it default to articles about the app? Do we even have any yet?

**Comment by Andrewsopoku** [comment]
@marvinmarnold @KevinWassermann94 is there a page on Freshdesk Portal Knowledge Base which is has "articles about the app", as requested in the acceptance criteria.

**Comment by KevinWassermann94** [comment]
@Andrewsopoku We can get the documentation for the app set up today/ tomorrow

**Comment by KevinWassermann94** [comment]
@Andrewsopoku You can link to here: https://support.nebra.com/support/solutions/24000003609

Content will be added to it, but link won't change

**Comment by marvinmarnold** [comment]
Closed by submission v1.0.4
