### ISSUE TITLE
Fix start screen when there are connectivity issues

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/maker-starter-app#143]
This is how the app looks when you have either no connectivity, or slow connectivity (before content loads):

![image](https://user-images.githubusercontent.com/357664/167470552-5040f8f9-4149-45c8-a704-e2070251a57e.png)

This is very misleading. In my case, I have a number of hotspots linked, but still get this. 

The desired behavior would be to show some placeholder text (such as "Loading..."), rather than 0 hotspots.

**Acceptance criteria**
- Display loader while establishing state.
- Display "Unable to fetch information" if request failed.
- Ability to refresh by pulling down or pressing a button. Provide some hint that this is possible.

**Comment by KevinWassermann94** [comment]
We should consider caching the hotspots in case the API is unavailable

**Comment by vpetersson** [comment]
Yeah caching could work here.

**Comment by marvinmarnold** [comment]
Closed by submission v1.0.4
