### ISSUE TITLE
Submit to Apple iphone App Store

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#15]

**Comment by Andrewsopoku** [comment]
Metadata needed before iOS can be submitted for App review can be found here.
https://help.apple.com/app-store-connect/#/devfc3066644

**Comment by Louisreed** [comment]
Hi Marvin, I attempted the video again on Friday but ran into the same issues! I'm going to try again today with another device. Will keep you posted.On 26 Mar 2022 18:51, Marvin Arnold ***@***.***> wrote:
@Louisreed what is the status of the video?

**Comment by Andrewsopoku** [comment]
@Louisreed please what specific issues are you having?

**Comment by Louisreed** [comment]
@Andrewsopoku "Error - Unable to find hotspot" after selecting the discovered hotspot...

**Comment by Andrewsopoku** [comment]
@marvinmarnold could it be about adding Louis' hotspot ETH MAC to our onboarding server?

**Comment by Louisreed** [comment]
@Andrewsopoku @marvinmarnold Sorry guys I'm getting another issue! Please see image attached. This happens at the same stage when trying to add the hotspot.

<img width="193" alt="Screenshot 2022-03-29 at 01 51 28" src="https://user-images.githubusercontent.com/9106988/160511034-08cf3478-69db-4ab3-ade7-a7bdf93fdf8a.png">

**Comment by marvinmarnold** [comment]
@posterzh can you publish a new release to the Google Play store?

**Comment by posterzh** [comment]
Ok, I will.

**Comment by marvinmarnold** [comment]
@posterzh is your work for this done? Can I create an APK and publish?

**Comment by marvinmarnold** [comment]
@Andrewsopoku after pulling from master, the built result points to the wrong bundle. Can you see if anything was missed as part of https://github.com/NebraLtd/maker-starter-app/pull/82?

![Screen Shot 2022-04-01 at 9 19 49 PM](https://user-images.githubusercontent.com/1311030/161361921-decb681b-d9ad-4ab4-a090-57674cb51413.png)

**Comment by Andrewsopoku** [comment]
@marvinmarnold It appears @posterzh changed for only android. I have created a PR here https://github.com/NebraLtd/maker-starter-app/pull/83 for iOS bundle ID change

**Comment by marvinmarnold** [comment]
Made an initial submission to Apple

**Comment by marvinmarnold** [comment]
@Andrewsopoku can you push a new build to iphone with the recent changes?

**Comment by marvinmarnold** [comment]
@Andrewsopoku doesn't look like there's a new build. Any blockers?

**Comment by Andrewsopoku** [comment]
@marvinmarnold I distributed one, hours ago 
https://appstoreconnect.apple.com/apps/1617299471/testflight/ios/93caf7ed-a1dc-41fa-a80a-25d2dccb9907

**Comment by marvinmarnold** [comment]
Thanks for pointing that out. I do see it in TestFlight, thought it would show up on the main page. Let's talk tomorrow about submitting for re-review.

**Comment by marvinmarnold** [comment]
v1.0.1 has been released and is in the app store
