### ISSUE TITLE
Add dashboard as an extra tab 

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/maker-starter-app#152]
Similar to #139 we should add dashboard as an extra tab. Even if, to start with, it's just a button that opens a browser window to Dashboard of similar it would be good to advertise it from the app

**Acceptance criteria**
- Free Trial button also opens this window: https://github.com/NebraLtd/maker-starter-app/issues/153
- Test responsiveness of Dashboard design on iPhone and Android. Create follow up tickets for any issues.

**Comment by marvinmarnold** [comment]
@Louisreed needs design

**Comment by Andrewsopoku** [comment]
@Louisreed please i dont seem to find the design on Figma. Can you share a link to it?

**Comment by Louisreed** [comment]
@Andrewsopoku https://www.figma.com/file/iIK2dbnE5TbIbar1B4olzM/Nebra-Design-System?node-id=3604%3A11777

**Comment by marvinmarnold** [comment]
@Andrewsopoku I updated the AC to check the responsive layout on mobile.

**Comment by marvinmarnold** [comment]
Published v1.0.5 to both stores. Waiting on approval.
