### ISSUE TITLE
Stuck on "updating hotspot" when trying to onboard

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#160]
Using v1.0.3 on iPhone. After confirming location to assert, then:
![signal-2022-05-21-071954_002](https://user-images.githubusercontent.com/1311030/169651343-3913608b-d516-434d-905f-b1b5de359495.png)

stuck on updating hotspot:

<img width="414" alt="signal-2022-05-21-071526_001" src="https://user-images.githubusercontent.com/1311030/169651106-9381cb6b-37b7-4932-82c0-d4b6df1516a9.png">

Possibly related to "Failed to fetch" values:

```
21.05.22 07:07:11 (-0500)  gateway-config  2022-05-21 12:07:11,452 - [DEBUG] - gatewayconfig.processors.diagnostics_processor - (diagnostics_processor.py).read_diagnostics_and_get_ok -- /opt/gatewayconfig/processors/diagnostics_processor.py:(28) - Read diagnostics {'AN': 'jumpy-gingham-gibbon', 'APPNAME': 'ROCK Pi', 'BA': 'HELIUM-INDOOR-915-rockpi', 'BCH': 1363375, 'BN': 'dull-sky', 'BSP': None, 'BT': True, 'BUTTON': 154, 'CELLULAR': False, 'CONTAINS_FCC_IDS': ['2ARPP-GL5712UX', '2A3PA-ROCKPI4'], 'CONTAINS_IC_IDS': [], 'E0': 'XXX', 'ECC': True, 'ECCOB': True, 'FCC_IDS': ['2AZDM-HHRK4'], 'FR': '915', 'FRIENDLY': 'Nebra ROCK Pi 4 Indoor', 'FW': '2022.05.19.0', 'GPIO_PIN_BUTTON': 16, 'GPIO_PIN_LED': 18, 'IC_IDS': ['27187-HHRK4'], 'ID': 'XXX', 'KEY_STORAGE_BUS': '/dev/i2c-7', 'LOR': False, 'LTE': False, 'MAC': 'eth0', 'MC': 'Failed to Fetch', 'MD': 'Failed to Fetch', 'MH': None, 'MN': 'Failed to Fetch', 'MR': 'Failed to Fetch', 'MS': False, 'OK': '11XTwHUxPd6DEeq13p7JE4bewBM5Nm6kF6vxKCNANaDZcRxJxwv', 'PF': False, 'PK': '11XTwHUxPd6DEeq13p7JE4bewBM5Nm6kF6vxKCNANaDZcRxJxwv', 'RE': 'UN123', 'RESET': 149, 'SPIBUS': 'spidev32766.0', 'STATUS': 156, 'TYPE': 'Full', 'VA': 'NEBHNT-HHRK4', 'XXX', 'firmware_short_hash': '4d4b348', 'last_updated': '12:07 UTC 21 May 2022', 'serial_number': 'XXX'}
```
https://dashboard.balena-cloud.com/devices/1af94fdfe4271c791a84afcbe5e4d7e2

**Comment by marvinmarnold** [comment]
@pritamghanghas have the values that cannot be fetched in the diagnostics above (MC, MD, MH, MN, etc) been correctly setup for the light miner?

**Comment by pritamghanghas** [comment]
@marvinmarnold  changes are in gateway-rs based light-hotspot branches. Master is not carry any change for these right now. Is it related to the stopped containers on test device that we discussed on slack?

**Comment by marvinmarnold** [comment]
@pritamghanghas this device is running in HELIUM-INDOOR-915-ROCKPI. Do we expect these values to be populated on the current helium-miner-software production branch?

**Comment by pritamghanghas** [comment]
> @pritamghanghas this device is running in HELIUM-INDOOR-915-ROCKPI. Do we expect these values to be populated on the current helium-miner-software production branch?

Yes, on current one we haven't changed anything yet as helium haven't stopped sync yet.

**Comment by posterzh** [comment]
I moved a rockpi besides me into the same fleet and tested the onboarding with Android phone. But I couldn't reproduce and onboarding went well.
Even simulating the onboarding with the hotspot ID from (https://dashboard.balena-cloud.com/devices/1af94fdfe4271c791a84afcbe5e4d7e2) went well.
There might be some iPhone specific issue.

**Comment by marvinmarnold** [comment]
@posterzh @Andrewsopoku I tested on Android and after pressing 'register hotspot', a prompt shows up asking me how I want to follow the deep link (open with Firefox or Chrome). After selecting Chrome, the official Helium app opens.

This seems to be the missing piece on iOS. For some reasons, the deep link isn't being correctly triggered.

**Comment by Andrewsopoku** [comment]
I believe you had this issue during onboarding. 
I have tried replicating the issue but still no luck.
Are you able to assert location?
Are you sure the build you have  doesn't have your address hardcoded?

**Comment by marvinmarnold** [comment]
Weird, I can no longer replicate this @posterzh @Andrewsopoku. I finally onboarded the hotspot with my iPhone, without a problem. Location assertion is also working fine. Will close this, even though I have no clue what changed.
