### ISSUE TITLE
Standardize  analytics nomenclature

### ISSUE THREAD

**Issue by Andrewsopoku** [NebraLtd/maker-starter-app#174]
Related to https://github.com/NebraLtd/hm-dashboard/issues/1084
**source_scope-action**
app_hotspot-onboarded

- sources:  app
- scopes: home, hotspot, support, dashboard
- actions: new, opened, location_asserted,  transferred, antenna_updated, address_copied 

**Acceptance Criteria**
- [x] The standard name scheme is `source.scope_subscope.action`
- [x] Actions: For every action button and page view

**Comment by Andrewsopoku** [comment]
@marvinmarnold https://github.com/NebraLtd/hm-dashboard/issues/1244 is a separate issue.

**Comment by marvinmarnold** [comment]
You are right, thanks for pointing that out.

**Comment by marvinmarnold** [comment]
App v1.0.6 submitted to both stores
