### ISSUE TITLE
Rename application to `Nebra Helium App`

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#25]
Rename your application using [React Native Rename](https://github.com/junedomingo/react-native-rename). You will want to pass in the custom bundle identifier for [Android](https://developer.android.com/studio/build/configure-app-module#set_the_application_id) and also change it manually for [iOS](https://developer.apple.com/documentation/appstoreconnectapi/bundle_ids).

https://github.com/NebraLtd/maker-starter-app/blob/0d2aba3f08e9c7ec0d8d57f4f0667e626f38b1ad/README.md?plain=1#L10

**Acceptance criteria**
- The launcher name should be "Nebra Helium App"
- Bundle ID should be com.nebra.helium.app

**Comment by Andrewsopoku** [comment]
@marvinmarnold can i pick up this issue?

**Comment by marvinmarnold** [comment]
Yes please

**Comment by Andrewsopoku** [comment]
@marvinmarnold please what bundle id should be used? eg. com.nebra.nebrahelium

**Comment by Andrewsopoku** [comment]
@marvinmarnold "Nebra Helium App" seems off, as non of the apps on my phone ends with "App". How about going with just "Nebra Helium". And also some part may be ellipsed on some phones because it is long. Thoughts?

**Comment by marvinmarnold** [comment]
@Andrewsopoku based on [Slack](https://nebraltd.slack.com/archives/C0XGF69SN/p1646412420070209?thread_ts=1646410959.701439&cid=C0XGF69SN), let's go with `Nebra` (launcher) / `Nebra Hotspot` (everywhere else).

**Comment by Andrewsopoku** [comment]
Well noted. Thank you.
