### ISSUE TITLE
Update splash screen and icons

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#30]
**Acceptance criteria**
- Splash screen should be displayed for both Android and iOS
- Files in native directories should be automatically generated based on react-native sources
- Primary app logo should be generated
- The splash screen should blend in with the frame background seamlessly on all phone sizes

**Comment by posterzh** [comment]
Current launcher icon and splash screen on Android 10 motor e.

**Launcher Icon**
![image](https://user-images.githubusercontent.com/91350131/157156517-68dc1a5f-215f-4a63-80c5-8b756a19462f.png)

**Splash Screen**
![image](https://user-images.githubusercontent.com/91350131/157156508-f7e26dfd-1607-497a-a1a6-b452f1c1905a.png)

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/38
