### ISSUE TITLE
Implement transfer

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#32]
**Acceptance criteria**
- BLE connection not required
- User always pays for transfer
- Hotspot address prefilled and not editable based on the hotspot that was selected form the homepage

**Comment by Andrewsopoku** [comment]
I guess we will hide both "Assert Location" and "Transfer Hotspot", and use them later when it becomes a necessity.

**Comment by marvinmarnold** [comment]
@Andrewsopoku any thoughts on debugging this when going through location assert?

![Screenshot_20220311-121445](https://user-images.githubusercontent.com/1311030/157915351-3f973e19-628c-4cc6-90e8-d23d554ba616.png)

**Comment by posterzh** [comment]
I will.

**Comment by posterzh** [comment]
Declaring permissions in `AndroidManifest.xml` is not enough for requesting a permission in Android App. Android OS needs app to implement [`Request the runtime permission`](https://developer.android.com/training/permissions/requesting).
![image](https://user-images.githubusercontent.com/91350131/158161864-0f9a0865-0c64-41e1-86b6-8c4449e21ebe.png)

**Comment by posterzh** [comment]
@marvinmarnold Running `Assert Location` without running `Add Hotspot` previously makes the App couldn't use BLE, since checking BLE runtime permission is only executed in `Add Hotspot`.

**Comment by marvinmarnold** [comment]
@Louisreed this will also need mocks

**Comment by marvinmarnold** [comment]
![Screen Shot 2022-03-16 at 10 15 19 AM](https://user-images.githubusercontent.com/1311030/158624156-1dbc4191-f269-4027-8ab7-3d6707d161e0.png)
![Screen Shot 2022-03-16 at 10 15 48 AM](https://user-images.githubusercontent.com/1311030/158624161-293321f8-70cb-49c3-8c48-04a85082469f.png)
![Screen Shot 2022-03-16 at 10 16 04 AM](https://user-images.githubusercontent.com/1311030/158624165-1a36da6a-9ef4-45ab-9e4b-1a0d58012f81.png)

**Comment by posterzh** [comment]
Addressed by https://github.com/NebraLtd/maker-starter-app/pull/57
