### ISSUE TITLE
Distribute build for internal testing

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#35]
The app needs to be circulated internally before being submitted. 

**Acceptance criteria**
- Instructions for creating and installing the binary

**Comment by posterzh** [comment]
**How to build Android apk for distributing:**
1. Open `android` subdirectory of `maker-starter-app` in Android Studio.
![image](https://user-images.githubusercontent.com/91350131/157296871-44be0cf6-15aa-47ac-9149-da2f68b53f94.png)

2. Click `Buid/Generate Signed Bundle/APK...`.
![image](https://user-images.githubusercontent.com/91350131/157297169-0f936353-48d3-4dba-95a1-3de1d9c00d8e.png)

3. Follow the steps to the end.

4. A signed apk will be generated in `android/app/release` subdirectory. This apk can be distributed to the testers.
![image](https://user-images.githubusercontent.com/91350131/157297634-7316856b-a85e-4d9c-af94-00b38a5dd03e.png)

5. Done

**Comment by marvinmarnold** [comment]
@Louisreed in order to be accepted by the Apple store, we need the video. Good old chicken and egg. 

![Screen Shot 2022-03-09 at 1 48 56 PM](https://user-images.githubusercontent.com/1311030/157522405-4e064a4e-5a2d-404c-8e0e-ba828f3140cd.png)


CC @shawaj @vpetersson ^^

**Comment by marvinmarnold** [comment]
But I think I read the email wrong. We can still use Test Flight in the meantime, we just can't promote it to Beta?

**Comment by Louisreed** [comment]
@marvinmarnold Also it says it requires the video to be of an iOS device. Do you have this available yet?

**Comment by marvinmarnold** [comment]
You should have received an invite. Because the app didn't get approved, we have to add people to a group instead of directly to the build.

**Comment by Louisreed** [comment]
@marvinmarnold Thanks I've got it, I'll get the video completed asap.

**Comment by marvinmarnold** [comment]
Great we can close this now. I was also able to produce APKs following these steps.
