### ISSUE TITLE
Remove unnecessary CAMERA permission

### ISSUE THREAD

**Issue by posterzh** [NebraLtd/maker-starter-app#51]
Since Nebra maker app doesn't use QR onboarding feature, declaring CAMERA permission in Android and iOS project is unnecessary. Otherwise, we need to explain about the need of CAMERA permission in the privacy policy on Google Play.

**Acceptance criteria**
- Android app doesn't require CAMERA permission in runtime.
- Google Play Store shouldn't complain about privacy policy to describe the CAMERA permission
- iOS app doesn't require CAMERA permission

**Comment by marvinmarnold** [comment]
@posterzh @Andrewsopoku can this be closed?

**Comment by posterzh** [comment]
@marvinmarnold Yes, this can be closed. @Andrewsopoku fixed iOS permission and this issues was postponed to be closed until I fix the Android.
