### ISSUE TITLE
Homepage should list all hotspots owned

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#54]
**Acceptance criteria**
- Add hotspot button large at top of page
- App landing page should list the owner's hotspots, including: animal name, online status in text, and location.
- List all hotspots, even if not owned by Nebra
- When you click on a hotspot, takes you to a Select Action Page
- If no hotspots exist, a message should be displayed on the page

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/56
