### ISSUE TITLE
Select Action Page

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#55]
**Acceptance criteria**
- Should be displayed after a hotspot is selected from the homepage
- Title: Animal name
- Two buttons: Update location/antenna and transfer ownership
- Jump to this page by clicking anywhere within the box of a hotspot listing, not just the three dots.

**Comment by Andrewsopoku** [comment]
@marvinmarnold @posterzh instead of taking user to a new page, can an action sheet which will pop up when the user select a hotstop be used?

**Comment by posterzh** [comment]
@Andrewsopoku It makes sense to me.

**Comment by marvinmarnold** [comment]
@Andrewsopoku the work for this is different than what is defined in the acceptance criteria, specifically title should be "Hotspot Settings" and subtitle should be animal name + PK.

I don't feel strongly about the original AC. But I want to make sure we are referencing them while we do our work.

What work is still needed on this?

**Comment by Andrewsopoku** [comment]
@marvinmarnold the AC wasn't strictly sticked to because a sheet was used instead of page. 
What is left is making the entire hotspot item clickable.

**Comment by marvinmarnold** [comment]
@Andrewsopoku I'm moving this back to In Progress, I'm not aware of an open PR

**Comment by Andrewsopoku** [comment]
That's fine. But a PR was opened which addressed the first 3 ACs. https://github.com/NebraLtd/maker-starter-app/pull/61. The PR has been closed.

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/109
