### ISSUE TITLE
Integrating Sentry for automatic reporting of errors and exceptions

### ISSUE THREAD

**Issue by Andrewsopoku** [NebraLtd/maker-starter-app#59]
We want to integrate Sentry's React Native SDK to enable automatic reporting of errors and exceptions, and identify performance issues in app. 

Acceptance Criteria:
- Should log all exceptions.
- Should log all native runtime app or device related crashes.

**Comment by Andrewsopoku** [comment]
@marvinmarnold sentry set up will require [dsn](https://docs.sentry.io/product/sentry-basics/dsn-explainer/).

**Comment by marvinmarnold** [comment]
@Andrewsopoku I just invited you to Sentry. LMK if you can access the DSN directly from there. In either case, I've also added it to 1Password. Thanks for making the issue.

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/86
