### ISSUE TITLE
Make Assert Location and Transfer Device buttons disabled

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#62]
We want to record a video of app functionality ASAP. We want to show assert location and device transfer so that Apple will know it's a feature we are working on that is not yet ready.

**Acceptance criteria**
- Add Hotspot button can be clicked
- Assert location button greyed out and not clickable
- Transfer device button added back in and greyed out

**Comment by Andrewsopoku** [comment]
@marvinmarnold Assert location and Transfer device buttons are no more on the homepage so i'm not sure i get you.

**Comment by posterzh** [comment]
@Andrewsopoku We need to place these buttons from the earlier git history, IMO.

**Comment by marvinmarnold** [comment]
Ah OK great. Then the we should grey out the options in this that are not yet ready: https://github.com/NebraLtd/maker-starter-app/pull/61

I'm going to close this and make the comment there. Thanks.
