### ISSUE TITLE
[iOS] Missing styling

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/maker-starter-app#63]
![IMG_0761](https://user-images.githubusercontent.com/357664/160108869-9f80811e-4107-482d-aaf8-966fc9c87000.PNG)

Looks like this is missing the Nebra styling

Ping @Louisreed

**Comment by Andrewsopoku** [comment]
@vpetersson Please did you run it in dark mode?

**Comment by Louisreed** [comment]
@vpetersson @Andrewsopoku Yes I think that's the dark mode missing the styling. Which needs global changes!

**Comment by vpetersson** [comment]
> @vpetersson Please did you run it in dark mode?

My phone is set to 'auto' so it shouldn't be dark mode.

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/67
