### ISSUE TITLE
[iOS] More missing styling

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/maker-starter-app#64]
![AC5D9DB7-1008-4F00-B387-BBD6E112B954_1_102_o](https://user-images.githubusercontent.com/357664/160108497-b306aa81-7d5c-4ff9-a1ff-62b730a8a953.jpeg)

This page is also missing the Nebra styling

Ping @Louisreed

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/67
