### ISSUE TITLE
[iOS] Missing hotspots

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/maker-starter-app#65]
![IMG_0763](https://user-images.githubusercontent.com/357664/160108983-5b760eba-6c5f-448e-84dc-20fa580b182b.PNG)
 
As you can see, the top says '8 Hotspot(s)', however only three are showing up.

**Comment by Andrewsopoku** [comment]
@vpetersson Please I'm unable to replicate the issue.

I tried with an owner address with 9 hotspots and all showed. Is it possible to get the owner address you used?

<img width="auto" height="600" src="https://user-images.githubusercontent.com/20680743/160213158-5fe5963a-3654-4603-8899-ff331d8bf714.png"/>

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/67
