### ISSUE TITLE
Release first production version to Google Play Store

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#73]
# @posterzh 
1. Disable device transfer
2. Enable add hotspot
3. Enable assert location
4. Create APK and share with @Louisreed 
5. Update register hotspot button so that assert location flow is correct

# @marvinmarnold 
1. Create a signing certificate
2. Add cert to 1Password
3. Build, sign, upload to Play Store
4. Update store copy and images
5. Publish

**Comment by marvinmarnold** [comment]
This has been published and is waiting approval.

**Comment by marvinmarnold** [comment]
Released an initial version: https://play.google.com/store/apps/details?id=com.nebra.helium.maker

Will close this at the end of the sprint when a more stable version is out.

**Comment by posterzh** [comment]
@marvinmarnold Thank you.

**Comment by marvinmarnold** [comment]
v1.0.1 released
