### ISSUE TITLE
Welcome page improvement 

### ISSUE THREAD

**Issue by Andrewsopoku** [NebraLtd/maker-starter-app#74]
We need to improve the look and feel of the welcome page.

<img height="400" width="auto" src="https://user-images.githubusercontent.com/20680743/160903809-878c697c-59b7-4ee3-9ef9-890b9a6ed52d.png"/>

**Acceptance Criteria**
- New mockup for the welcome page.
- Implementation of the mockup

**Comment by Andrewsopoku** [comment]
@Louisreed please are you able redesign the welcome page above and share a mock up with us?

**Comment by Louisreed** [comment]
@Andrewsopoku I'm on it!

**Comment by Louisreed** [comment]
@Andrewsopoku Something like this? https://www.figma.com/file/6l7k7BRmW98AMmRxV01iVT/App?node-id=9%3A2

![Welcome-Page](https://user-images.githubusercontent.com/9106988/161245822-1acfad7c-d9ec-4b7f-bcad-0b6b34a399f6.png)

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/110
