### ISSUE TITLE
Fix last step in onboarding

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#78]
On this page:
![image](https://user-images.githubusercontent.com/1311030/160907404-63ca40b2-e197-4c4b-9ef4-2de917971420.png)

Crash report:
![image](https://user-images.githubusercontent.com/1311030/160907004-2802f44c-17e3-47a0-a29c-c3ada653a257.png)

**Acceptance criteria**

**For Onboarding**
- Title should say: "REGISTERING HOTSPOT"
- Subtitle should say: "Press the button below to view your hotspots. But be patient, it can take a few minutes for your new hotspot to show".
- "Go to wallet" should be renamed "Show My Hotspots"
- Button should take the user back to the homepage / hotspots list page

**For Updating**
- Title should say: "UPDATING HOTSPOT"
- Subtitle should say: "Press the button below to view your hotspots. But be patient, it can take a few minutes for your new update to show".
- "Go to wallet" should be renamed "Show My Hotspots"
- Button should take the user back to the homepage / hotspots list page

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/108
