### ISSUE TITLE
Contents don't always fit on screen

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#79]
Sometimes the top of the Home page screen is cut off:
convo: https://nebraltd.slack.com/archives/C024BNQ1Y6T/p1648671819116959
![image](https://user-images.githubusercontent.com/1311030/160933404-a3eb4e50-ac0a-41ae-b02f-876c0bb5b86d.png)

**Acceptance Criteria**
- Content of the home page screen should be contained

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/85
