### ISSUE TITLE
Android app crashes: Nebra keeps stopping

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#80]
Video: https://nebraltd.slack.com/archives/C0XGF69SN/p1648686501123209?thread_ts=1647279479.807949&cid=C0XGF69SN

**Comment by marvinmarnold** [comment]
@posterzh crash report from Google Play

<img width="1178" alt="Screen Shot 2022-04-04 at 3 40 34 PM" src="https://user-images.githubusercontent.com/1311030/161628367-b11d644d-3121-4006-aa9e-2724672aa6ba.png">

[logcat.txt](https://github.com/NebraLtd/maker-starter-app/files/8413056/logcat.txt)

**Comment by posterzh** [comment]
The full logcat file is very helpful. I will fix.

**Comment by marvinmarnold** [comment]
BTW this is what makes me think that the app is still under review and not yet rejected, despite the crash

![image](https://user-images.githubusercontent.com/1311030/161779766-acbdbd96-9836-414f-83d9-a0b019abcd31.png)

**Comment by posterzh** [comment]
The reason of crashing is that the splash image is too big.
This is from `logcat.txt`:
`04-01 14:34:59.258: E/AndroidRuntime(12745): java.lang.RuntimeException: Canvas: trying to draw too large(128556540bytes) bitmap.
04-01 14:34:59.258: E/AndroidRuntime(12745): 	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)`

Need to replace the splash image to a smaller size.
