### ISSUE TITLE
Share button not working

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#88]
The "share" button - it tries to share makerappscheme://hotspot/11qFNi5gNpm4zWBUbbrJ1BVhUgEfwM3M73nhmasURh8rBGeButb

**Acceptance Criteria**
- Share option should be removed

**Comment by marvinmarnold** [comment]
@posterzh @Andrewsopoku can you add more details and acceptance criteria to this?

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/123
