### ISSUE TITLE
Increase touch size

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#89]
Android flagged touch size as an issue in the pre-launch report.

<img width="516" alt="Screen Shot 2022-04-04 at 3 42 54 PM" src="https://user-images.githubusercontent.com/1311030/161629590-bbb4e121-8b67-433f-a4e7-a99fbfb87b6f.png">

**Comment by Andrewsopoku** [comment]
@marvinmarnold this issue has been fixed. Can i closed it?

**Comment by marvinmarnold** [comment]
@Andrewsopoku yes, please link to the PR that closed it
