### ISSUE TITLE
Spike: Determine which build tool to use for production

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#9]
Fastlane looks like a good option. Timebox this to 2h.

**Comment by posterzh** [comment]
@marvinmarnold @Andrewsopoku I agree **Fastlane** is the best tool as a production tool for this project. It supports well. When we are using **Fastlane**, additional consideration might be:
- Determine which CI tool to run test(https://docs.fastlane.tools/getting-started/ios/running-tests/)
- Add more test cases to the project to cover onboarding logic
- Invite beta testers(QA) to the beta deployment(https://docs.fastlane.tools/getting-started/android/beta-deployment/)

**Comment by Andrewsopoku** [comment]
@marvinmarnold @posterzh We can consider Codemagic too. Although the name sound fancy, it looks promising.

https://docs.codemagic.io/yaml-quick-start/building-a-react-native-app/

**Comment by marvinmarnold** [comment]
@Andrewsopoku @vpetersson, Zhang and I are leaning towards Fastlane. Andrews, I believe you have experience with Fastlane, not Codemagic. That's important. Codemagic looks cool, but it has more features than we need now and it feels too new and shiny, whereas Fastlane is more battle tested. 

I think we are going to quickly regret doing the build process by hand, without any tooling. And Fastlane will give us some nice features like automated screenshot captures.

Viktor, we can break the process up into three steps: build, signing, and publish. My understanding is that you are OK with having automated builds on Github workflows as long as signing and publishing can be done locally. Is that right? Would you be comfortable also signing and publishing from a workflow as long as the key is a subkey or signing-only key?

Other reading:
- Highway but its no longer maintained: https://www.netguru.com/blog/the-introduction-to-highway-our-new-build-system
- https://www.thinslices.com/blog/automating-the-build-and-deployment-of-react-native-apps
Mac first
- https://www.bitrise.io
- https://appcircle.io/

**Comment by vpetersson** [comment]
> Viktor, we can break the process up into three steps: build, signing, and publish. My understanding is that you are OK with having automated builds on Github workflows as long as signing and publishing can be done locally. Is that right? Would you be comfortable also signing and publishing from a workflow as long as the key is a subkey or signing-only key?

Yeah i'm OK with automated builds. However, I'm not sure if it is possible to break those things apart in the iOS world at least. However, I'm not exactly up to date with these things.

**Comment by marvinmarnold** [comment]
We have consensus that we'll do completely manual releases to start.
