### ISSUE TITLE
Fix low contrast

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#91]
Identified in Android pre-launch report

<img width="446" alt="Screen Shot 2022-04-04 at 3 51 15 PM" src="https://user-images.githubusercontent.com/1311030/161630026-5849b8f2-0588-495d-8019-dd663784f998.png">

**Comment by Andrewsopoku** [comment]
Closed with https://github.com/NebraLtd/maker-starter-app/pull/110
