### ISSUE TITLE
Add more detailed Bluetooth usage info for iPhone

### ISSUE THREAD

**Issue by marvinmarnold** [NebraLtd/maker-starter-app#98]
Guideline 5.1.1 - Legal - Privacy - Data Collection and Storage

We noticed that your app requests the user’s consent to access the Bluetooth, but doesn’t sufficiently explain the use of the Bluetooth in the purpose string.

Next Steps

Please revise the purpose string in your app’s Info.plist file for the Bluetooth to explain why your app needs access and include an example of how the user's data will be used.

You can modify your app's Info.plist file using the property list editor in Xcode.

Resources

- See examples of [helpful, informative purpose strings](https://developer.apple.com/ios/human-interface-guidelines/app-architecture/requesting-permission/).
- Review a list of [relevant property list keys](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW18).

**Comment by marvinmarnold** [comment]
@Andrewsopoku looks great. Just capitalize `Bluetooth`.

**Comment by Andrewsopoku** [comment]
@marvinmarnold a PR has been created. https://github.com/NebraLtd/maker-starter-app/pull/102

**Comment by Andrewsopoku** [comment]
Close with https://github.com/NebraLtd/maker-starter-app/pull/102
